FROM node:16.13-alpine3.12

EXPOSE 5000

WORKDIR /usr/src/app/frontend

ADD /bin/docker-entrypoint.sh /usr/src/app/bin/

RUN chmod 777 /usr/src/app/bin/docker-entrypoint.sh \
    && ln -s /usr/src/app/bin/docker-entrypoint.sh /

ENTRYPOINT ["docker-entrypoint.sh"]

# start the app
CMD [ "yarn", "start"]



